name: Check WordPress Updates

on:
  schedule:
    # Run at 00:00 on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      schedule_day:
        description: 'Day of the month to run (1-31)'
        required: false
        default: '1'
      schedule_time:
        description: 'Time to run (HH:MM)'
        required: false
        default: '00:00'
      timezone:
        description: 'Timezone for the schedule'
        required: false
        default: 'UTC'
      check_type:
        description: 'Type of updates to check'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - plugins
          - themes

jobs:
  check-updates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check for updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STAGING_SITE_URL: ${{ vars.STAGING_SITE_URL }}
          STAGING_SITE_AUTH_TOKEN: ${{ secrets.STAGING_SITE_AUTH_TOKEN }}
          CHECK_TYPE: ${{ github.event.inputs.check_type || 'all' }}
        run: |
          # Run the update check and ensure only JSON is written to the file
          # Redirect stdout to updates.json and stderr to the console
          node scripts/check-updates.js 2>&1 > updates.json || {
            echo "Error: Failed to generate updates report"
            exit 1
          }
          
          # Validate the JSON file
          if ! jq empty updates.json 2>/dev/null; then
            echo "Error: Generated file is not valid JSON"
            exit 1
          fi

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "CHANGES_FOUND=true" >> $GITHUB_ENV
            echo "Changes found in the repository"
            # Generate a unique branch name using timestamp
            echo "SYNC_BRANCH=sync-wordpress-content-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          else
            echo "CHANGES_FOUND=false" >> $GITHUB_ENV
            echo "No changes found in the repository"
          fi

      - name: Create Pull Request to Main
        id: create-pr
        if: env.CHANGES_FOUND == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_FOR_TECHOPS_AUTOMATION }}
          base: main
          branch: ${{ env.SYNC_BRANCH }}
          title: "Sync WordPress Update Check Reports from Staging Site"
          body: |
            This PR syncs update check report to main branch.
            
            Changes include:
            - Checked for updates on plugins and themes
            - Created GitHub issues if updates are available
            - Generated updates.json with details
          delete-branch: false

      - name: Handle PR Creation Failure
        if: failure()
        run: |
          echo "Failed to create PR. Please check the workflow logs for more details." 