name: WordPress Activation Sync
on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  sync-activation:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deployment
        run: |
          echo "Waiting 60 seconds for content deployment to complete..."
          echo "This ensures all files are properly deployed to the staging site."
          sleep 60
          echo "Proceeding with activation sync..."
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Sync theme activation states
        id: theme_sync_states
        env:
          LIVE_SITE_AUTH_TOKEN: ${{ secrets.LIVE_SITE_AUTH_TOKEN }}
          STAGING_SITE_AUTH_TOKEN: ${{ secrets.STAGING_SITE_AUTH_TOKEN }}
          LIVE_SITE_URL: ${{ github.event.inputs.live_site_url || vars.LIVE_SITE_URL }}
          STAGING_SITE_URL: ${{ github.event.inputs.staging_site_url || vars.STAGING_SITE_URL }}
        run: |
          echo "Starting theme activation sync..."
          ERROR_LOG=$(mktemp)
          
          if ! node scripts/sync-theme-activation.js 2>&1 | tee -a "$ERROR_LOG"; then
            ERROR_MSG=$(cat "$ERROR_LOG" | grep -A 5 "error:" || cat "$ERROR_LOG")
            echo "theme_sync_successful=false" >> $GITHUB_OUTPUT
            echo "theme_sync_error<<EOF" >> $GITHUB_OUTPUT
            echo "$ERROR_MSG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "❌ Theme activation sync failed with error:"
            echo "$ERROR_MSG"
            rm "$ERROR_LOG"
            exit 1
          fi
          
          if [[ -f wp-content/themes/theme-sync-report.json ]]; then
            REPORT_CONTENT=$(cat wp-content/themes/theme-sync-report.json)
            if echo "$REPORT_CONTENT" | grep -q '"sync_status":"error"'; then
              echo "theme_sync_successful=false" >> $GITHUB_OUTPUT
              echo "theme_sync_error<<EOF" >> $GITHUB_OUTPUT
              echo "$REPORT_CONTENT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
              echo "❌ Theme sync completed with errors. Check the report for details."
              exit 1
            fi
            
            echo "theme_sync_successful=true" >> $GITHUB_OUTPUT
            echo "✅ Theme activation sync completed successfully"
          else
            echo "theme_sync_successful=false" >> $GITHUB_OUTPUT
            echo "theme_sync_error=No theme sync report generated" >> $GITHUB_OUTPUT
            echo "❌ No theme sync report found"
            exit 1
          fi

      - name: Sync plugin activation states
        id: plugin_sync_states
        if: success() || failure()  # Run even if theme sync failed
        env:
          LIVE_SITE_AUTH_TOKEN: ${{ secrets.LIVE_SITE_AUTH_TOKEN }}
          STAGING_SITE_AUTH_TOKEN: ${{ secrets.STAGING_SITE_AUTH_TOKEN }}
          LIVE_SITE_URL: ${{ github.event.inputs.live_site_url || vars.LIVE_SITE_URL }}
          STAGING_SITE_URL: ${{ github.event.inputs.staging_site_url || vars.STAGING_SITE_URL }}
        run: |
          echo "Starting plugin activation sync..."
          ERROR_LOG=$(mktemp)
          
          if ! node scripts/sync-activation.js 2>&1 | tee -a "$ERROR_LOG"; then
            ERROR_MSG=$(cat "$ERROR_LOG" | grep -A 5 "error:" || cat "$ERROR_LOG")
            echo "plugin_sync_successful=false" >> $GITHUB_OUTPUT
            echo "plugin_sync_error<<EOF" >> $GITHUB_OUTPUT
            echo "$ERROR_MSG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "❌ Plugin activation sync failed with error:"
            echo "$ERROR_MSG"
            rm "$ERROR_LOG"
            exit 1
          fi
          
          if [[ -f wp-content/plugins/sync-report.json ]]; then
            REPORT_CONTENT=$(cat wp-content/plugins/sync-report.json)
            if echo "$REPORT_CONTENT" | grep -q '"sync_status":"error"'; then
              echo "plugin_sync_successful=false" >> $GITHUB_OUTPUT
              echo "plugin_sync_error<<EOF" >> $GITHUB_OUTPUT
              echo "$REPORT_CONTENT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
              echo "❌ Plugin sync completed with errors. Check the report for details."
              exit 1
            fi
            
            echo "plugin_sync_successful=true" >> $GITHUB_OUTPUT
            echo "✅ Plugin activation sync completed successfully"
          else
            echo "plugin_sync_successful=false" >> $GITHUB_OUTPUT
            echo "plugin_sync_error=No plugin sync report generated" >> $GITHUB_OUTPUT
            echo "❌ No plugin sync report found"
            exit 1
          fi

      - name: Upload theme sync report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theme-sync-report
          path: wp-content/themes/theme-sync-report.json
          retention-days: 7

      - name: Upload plugin sync report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plugin-sync-report
          path: wp-content/plugins/sync-report.json
          retention-days: 7

      - name: Check sync status
        if: always()
        run: |
          THEME_SYNC_SUCCESS=${{ steps.theme_sync_states.outputs.theme_sync_successful }}
          PLUGIN_SYNC_SUCCESS=${{ steps.plugin_sync_states.outputs.plugin_sync_successful }}
          
          if [[ "$THEME_SYNC_SUCCESS" != "true" ]]; then
            echo "::warning::Theme activation sync failed"
            echo "Theme sync error: ${{ steps.theme_sync_states.outputs.theme_sync_error }}"
          fi
          
          if [[ "$PLUGIN_SYNC_SUCCESS" != "true" ]]; then
            echo "::warning::Plugin activation sync failed"
            echo "Plugin sync error: ${{ steps.plugin_sync_states.outputs.plugin_sync_error }}"
          fi
          
          if [[ "$THEME_SYNC_SUCCESS" != "true" || "$PLUGIN_SYNC_SUCCESS" != "true" ]]; then
            exit 1
          fi

      - name: Add Sync Report Comment
        if: always()
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Activation Sync Status
            
            ### Theme Activation
            ${{ steps.theme_sync_states.outputs.theme_sync_successful == 'true' && '✅ Theme activation states synchronized successfully' || '❌ Theme activation sync failed' }}
            
            ${{ steps.theme_sync_states.outputs.theme_sync_successful != 'true' && format('#### Theme Error Details:{0}{1}', '\n```\n', steps.theme_sync_states.outputs.theme_sync_error) || '' }}
            ${{ steps.theme_sync_states.outputs.theme_sync_successful != 'true' && '\n```' || '' }}
            
            ### Plugin Activation
            ${{ steps.plugin_sync_states.outputs.plugin_sync_successful == 'true' && '✅ Plugin activation states synchronized successfully' || '❌ Plugin activation sync failed' }}
            
            ${{ steps.plugin_sync_states.outputs.plugin_sync_successful != 'true' && format('#### Plugin Error Details:{0}{1}', '\n```\n', steps.plugin_sync_states.outputs.plugin_sync_error) || '' }}
            ${{ steps.plugin_sync_states.outputs.plugin_sync_successful != 'true' && '\n```' || '' }}
            
            Please verify the theme and plugin states on the staging site. 