name: WordPress Content Sync
on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'WordPress site URL'
        required: true
        default: 'https://wordpress-1000690-5314661.cloudwaysapps.com'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"

      - name: Create directory structure
        run: |
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes
          # Create .gitignore if it doesn't exist
          if [ ! -f .gitignore ]; then
            echo "# Ignore ZIP files and temp files" > .gitignore
            echo "*.zip" >> .gitignore
            echo "*.tmp" >> .gitignore
            echo "wp-content/**/*.zip" >> .gitignore
            git add .gitignore
          fi
          echo "Directory structure created:"
          ls -R wp-content/

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x scripts/*.js
          echo "Script permissions:"
          ls -la scripts/

      - name: Verify script contents
        run: |
          echo "Content of download-content.sh:"
          cat scripts/download-content.sh
          echo -e "\nContent of process-plugins.js:"
          cat scripts/process-plugins.js
          echo -e "\nContent of process-themes.js:"
          cat scripts/process-themes.js

      - name: Download and process content
        env:
          WP_APP_USERNAME: ${{ secrets.WP_APP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_AUTH_TOKEN: ${{ secrets.WP_AUTH_TOKEN }}
          SITE_URL: ${{ inputs.site_url }}
        run: |
          echo "Starting content download with SITE_URL: $SITE_URL"
          echo "Testing API endpoints..."
          # Test plugins endpoint
          echo "Testing plugins endpoint..."
          curl -v -H "Authorization: Basic $WP_AUTH_TOKEN" "$SITE_URL/wp-json/techops/v1/plugins/list"
          echo -e "\n\nTesting themes endpoint..."
          curl -v -H "Authorization: Basic $WP_AUTH_TOKEN" "$SITE_URL/wp-json/techops/v1/themes/list"
          echo -e "\n\nProceeding with content sync..."
          bash ./scripts/download-content.sh

      - name: Cleanup temporary files
        if: always()
        run: |
          find wp-content -name "*.zip" -type f -delete
          find wp-content -name "*.tmp" -type f -delete
          echo "Cleanup completed. Current wp-content structure:"
          ls -R wp-content/

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          base: release
          title: 'feat: Update WordPress content'
          body: |
            Automated PR to sync WordPress content:
            - Updated wp-content/plugins
            - Updated wp-content/themes
            
            Note: All temporary and ZIP files have been cleaned up.
          branch: feat/wordpress-content-update
          commit-message: 'feat: Update WordPress content' 