name: WordPress Content Sync
# This workflow downloads WordPress content to main branch and creates a PR to release branch
on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'WordPress site URL'
        required: true
        default: 'https://wordpress-1000690-5314661.cloudwaysapps.com'
      staging_url:
        description: 'Staging site URL'
        required: true
        default: 'https://staging-wordpress-1000690-5314661.cloudwaysapps.com'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify branch
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Remote URL: $(git remote get-url origin)"
          echo "Git status:"
          git status

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"

      - name: Create directory structure
        run: |
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes
          # Create .gitignore if it doesn't exist
          if [ ! -f .gitignore ]; then
            echo "# Ignore ZIP files and temp files" > .gitignore
            echo "*.zip" >> .gitignore
            echo "*.tmp" >> .gitignore
            echo "wp-content/**/*.zip" >> .gitignore
            git add .gitignore
          fi
          echo "Directory structure created:"
          ls -R wp-content/

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x scripts/*.js
          echo "Script permissions:"
          ls -la scripts/

      - name: Test API Authentication
        env:
          WP_APP_USERNAME: ${{ secrets.WP_APP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_AUTH_TOKEN: ${{ secrets.WP_AUTH_TOKEN }}
          SITE_URL: ${{ inputs.site_url }}
        run: |
          echo "Testing API endpoints and authentication..."
          
          # Function to test endpoint
          test_endpoint() {
            local endpoint=$1
            local description=$2
            echo "Testing $description endpoint: $SITE_URL$endpoint"
            echo "Auth token format check..."
            if ! echo "$WP_AUTH_TOKEN" | base64 -d > /dev/null 2>&1; then
              echo "Error: WP_AUTH_TOKEN is not valid base64"
              exit 1
            fi
            
            # Test with curl
            echo "Making request to $description endpoint..."
            response=$(curl -s -w "\n%{http_code}" -H "Authorization: Basic $WP_AUTH_TOKEN" "$SITE_URL$endpoint")
            status_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')
            
            echo "Status code: $status_code"
            echo "Response headers:"
            curl -s -I -H "Authorization: Basic $WP_AUTH_TOKEN" "$SITE_URL$endpoint"
            echo "Response body:"
            echo "$body"
            
            if [ "$status_code" != "200" ]; then
              echo "Error: $description endpoint returned status $status_code"
              exit 1
            fi
            
            echo "$description endpoint test successful"
            echo "----------------------------------------"
          }
          
          # Test endpoints
          test_endpoint "/wp-json/techops/v1/plugins/list" "plugins"
          test_endpoint "/wp-json/techops/v1/themes/list" "themes"
          
          echo "API authentication tests completed successfully"

      - name: Download and process content
        if: success()
        env:
          WP_APP_USERNAME: ${{ secrets.WP_APP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_AUTH_TOKEN: ${{ secrets.WP_AUTH_TOKEN }}
          SITE_URL: ${{ inputs.site_url }}
        run: |
          echo "Starting content download with SITE_URL: $SITE_URL"
          bash ./scripts/download-content.sh

      - name: Cleanup temporary files
        if: always()
        run: |
          find wp-content -name "*.zip" -type f -delete
          find wp-content -name "*.tmp" -type f -delete
          echo "Cleanup completed. Current wp-content structure:"
          ls -R wp-content/

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Ensure we're on main and up to date
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Check for changes and commit to main
        id: check_changes
        run: |
          # Add all changes in wp-content
          git add wp-content/
          
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in wp-content directory"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            
            echo "Git status before commit:"
            git status
            
            # Commit changes to main branch
            git commit -m "feat: Update WordPress content"
            
            echo "Pushing changes to main branch..."
            git push origin main
            
            echo "Git log of recent commits:"
            git log -3 --oneline
          else
            echo "No changes detected in wp-content directory"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  sync-activation:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Sync activation states
        env:
          WP_APP_USERNAME: ${{ secrets.WP_APP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_AUTH_TOKEN: ${{ secrets.WP_AUTH_TOKEN }}
          STAGING_URL: ${{ inputs.staging_url }}
        run: |
          node scripts/sync-activation.js

      - name: Commit sync report
        if: always()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          if [[ -f wp-content/plugins/sync-report.json ]]; then
            git add wp-content/plugins/sync-report.json
            git commit -m "docs: Add activation sync report"
            git push origin main
          fi

      - name: Create Pull Request from main to release
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release
          head: main
          title: 'feat: Update WordPress content'
          body: |
            Automated PR to sync WordPress content from main to release:
            - Updated wp-content/plugins
            - Updated wp-content/themes
            - Synchronized plugin activation states
            
            Note: All temporary and ZIP files have been cleaned up.
            
            ## Changes Summary
            Branch being merged: `main` → `release`
            
            ## Verification
            - [ ] Changes are present in main branch
            - [ ] No sensitive files included
            - [ ] Directory structure is correct
            - [ ] Plugin activation states are synchronized
          commit-message: 'feat: Update WordPress content'
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          
      - name: Verify final state
        if: always()
        run: |
          echo "Final branch state:"
          git rev-parse --abbrev-ref HEAD
          
          echo "Recent commits in main:"
          git log -3 --oneline main
          
          echo "Recent commits in release:"
          git log -3 --oneline release
          
          echo "Branch difference:"
          git --no-pager diff main...release --stat 