name: WordPress Content Sync
# This workflow downloads WordPress content to main branch and creates a PR to release branch
on:
  workflow_dispatch:
    inputs:
      wordpress_site_url:
        description: 'WordPress Site URL'
        required: true
        default: 'https://techopsautomation.wisdmlabs.net'
      live_site_url:
        description: 'Live Site URL'
        required: true
      live_site_auth_token:
        description: 'Live Site Auth Token'
        required: true
        type: password
      staging_site_auth_token:
        description: 'Staging Site Auth Token'
        required: true
        type: password

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create directory structure
        run: |
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes
          
      - name: Make scripts executable
        run: chmod +x scripts/*.sh
        
      - name: Test API Authentication
        run: |
          curl -i -H "Authorization: Basic ${{ github.event.inputs.live_site_auth_token }}" \
            ${{ github.event.inputs.live_site_url }}/wp-json/techops/v1/plugins/list
          curl -i -H "Authorization: Basic ${{ github.event.inputs.staging_site_auth_token }}" \
            ${{ github.event.inputs.wordpress_site_url }}/wp-json/techops/v1/plugins/list
            
      - name: Download Content
        env:
          LIVE_SITE_URL: ${{ github.event.inputs.live_site_url }}
          LIVE_SITE_AUTH_TOKEN: ${{ github.event.inputs.live_site_auth_token }}
          STAGING_SITE_URL: ${{ github.event.inputs.wordpress_site_url }}
          STAGING_SITE_AUTH_TOKEN: ${{ github.event.inputs.staging_site_auth_token }}
        run: ./scripts/download-content.sh
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync/wordpress-content
          base: main
          title: 'Sync WordPress Content'
          body: |
            This PR syncs WordPress content from live to staging site.
            
            Changes include:
            - Updated plugins
            - Updated themes
            - Synchronized activation states
            
            Please review the changes before merging.

  sync-activation:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Sync activation states
        id: sync_states
        env:
          LIVE_SITE_AUTH_TOKEN: ${{ secrets.LIVE_SITE_AUTH_TOKEN }}
          STAGING_SITE_AUTH_TOKEN: ${{ secrets.STAGING_SITE_AUTH_TOKEN }}
          LIVE_SITE_URL: ${{ inputs.site_url }}
          STAGING_SITE_URL: ${{ inputs.staging_url }}
        run: |
          node scripts/sync-activation.js
          if [[ -f wp-content/plugins/sync-report.json ]]; then
            echo "sync_successful=true" >> $GITHUB_OUTPUT
          else
            echo "sync_successful=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit sync report
        if: steps.sync_states.outputs.sync_successful == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add wp-content/plugins/sync-report.json
          git commit -m "docs: Add activation sync report"
          git push origin main

      - name: Create Pull Request from main to release
        if: steps.check_changes.outputs.has_changes == 'true' && steps.sync_states.outputs.sync_successful == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release
          head: main
          title: 'feat: Update WordPress content'
          body: |
            Automated PR to sync WordPress content from main to release:
            - Updated wp-content/plugins
            - Updated wp-content/themes
            - Synchronized plugin activation states
            
            Note: All temporary and ZIP files have been cleaned up.
            
            ## Changes Summary
            Branch being merged: `main` → `release`
            
            ## Verification
            - [ ] Changes are present in main branch
            - [ ] No sensitive files included
            - [ ] Directory structure is correct
            - [ ] Plugin activation states are synchronized
          commit-message: 'feat: Update WordPress content'
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          
      - name: Verify final state
        if: always()
        run: |
          echo "Final branch state:"
          git rev-parse --abbrev-ref HEAD
          
          echo "Recent commits in main:"
          git log -3 --oneline main
          
          echo "Recent commits in release:"
          git log -3 --oneline release
          
          echo "Branch difference:"
          git --no-pager diff main...release --stat 