name: Process WordPress Updates

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of updates to process'
        required: true
        type: choice
        options:
          - 'all'
          - 'plugins'
          - 'themes'
        default: 'all'

jobs:
  process-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Process updates
        env:
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: |
          # Run the update processor and capture output
          npm run process-updates | tee processor_output.txt
          
          # Print the processing output
          echo "Update Processing Output:"
          cat processor_output.txt
          
          # Check if update_results.json exists and contains updates
          if [ -f "update_results.json" ]; then
            PROCESSED_COUNT=$(jq '.processed | length' update_results.json)
            if [ "$PROCESSED_COUNT" -gt 0 ]; then
              echo "UPDATES_PROCESSED=true" >> $GITHUB_ENV
            else
              echo "UPDATES_PROCESSED=false" >> $GITHUB_ENV
            fi
          else
            echo "UPDATES_PROCESSED=false" >> $GITHUB_ENV
          fi

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "CHANGES_FOUND=true" >> $GITHUB_ENV
            echo "Changes found in the repository"
            # Generate a unique branch name using timestamp
            echo "SYNC_BRANCH=sync-wordpress-content-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          else
            echo "CHANGES_FOUND=false" >> $GITHUB_ENV
            echo "No changes found in the repository"
          fi

      - name: Create Pull Request to Main
        id: create-pr
        if: env.CHANGES_FOUND == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_FOR_TECHOPS_AUTOMATION }}
          base: main
          branch: ${{ env.SYNC_BRANCH }}
          title: "Processed Wordpress Updates"
          body: |
            This PR merges WordPress content updates to main branch.
            
            Changes include:
            - Updated plugins
            - Updated themes
          delete-branch: false

      - name: Handle Failure
        if: failure()
        run: |
          echo "Failed to process updates or create PR. Check the logs for details."
          if [ -f "processor_output.txt" ]; then
            echo "Processor Output:"
            cat processor_output.txt
          fi 