name: WordPress Content Sync
# This workflow downloads WordPress content to main branch and creates a PR to release branch
on:
  workflow_dispatch:
    inputs:
      live_site_url:
        description: 'Live Site URL'
        required: true
        default: 'https://wordpress-1000690-5314661.cloudwaysapps.com'
      staging_site_url:
        description: 'Staging Site URL'
        required: true
        default: 'https://techopsautomation.wisdmlabs.net'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: . # This ensures the repo is checked out in the current directory
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create directory structure
        run: |
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes
          
      - name: Make scripts executable
        run: chmod +x scripts/*.sh
        
      - name: Test API Authentication
        run: |
          echo "Testing API authentication for live site..."
          LIVE_RESPONSE=$(curl -i -H "Authorization: Basic ${{ secrets.LIVE_SITE_AUTH_TOKEN }}" \
            ${{ github.event.inputs.live_site_url }}/wp-json/techops/v1/plugins/list)
          LIVE_STATUS=$(echo "$LIVE_RESPONSE" | grep "HTTP/" | awk '{print $2}')
          echo "Live site response status: $LIVE_STATUS"
          
          if [[ "$LIVE_STATUS" != "200" ]]; then
            echo "❌ Live site authentication failed with status $LIVE_STATUS"
            echo "Response: $LIVE_RESPONSE"
            exit 1
          fi
          
          echo "Testing API authentication for staging site..."
          STAGING_RESPONSE=$(curl -i -H "Authorization: Basic ${{ secrets.STAGING_SITE_AUTH_TOKEN }}" \
            ${{ github.event.inputs.staging_site_url }}/wp-json/techops/v1/plugins/list)
          STAGING_STATUS=$(echo "$STAGING_RESPONSE" | grep "HTTP/" | awk '{print $2}')
          echo "Staging site response status: $STAGING_STATUS"
          
          if [[ "$STAGING_STATUS" != "200" ]]; then
            echo "❌ Staging site authentication failed with status $STAGING_STATUS"
            echo "Response: $STAGING_RESPONSE"
            exit 1
          fi
          
          echo "✅ Authentication successful for both sites"

      - name: Check and Switch to Main Branch
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          echo "Current branch: $CURRENT_BRANCH"
          
          if [[ "$CURRENT_BRANCH" != "main" ]]; then
            echo "Not on main branch. Switching to main branch..."
            git checkout main
            git pull origin main
            echo "✅ Successfully switched to main branch"
          else
            echo "Already on main branch"
          fi
            
      - name: Download Content
        env:
          LIVE_SITE_URL: ${{ github.event.inputs.live_site_url }}
          LIVE_SITE_AUTH_TOKEN: ${{ secrets.LIVE_SITE_AUTH_TOKEN }}
          STAGING_SITE_URL: ${{ github.event.inputs.staging_site_url }}
          STAGING_SITE_AUTH_TOKEN: ${{ secrets.STAGING_SITE_AUTH_TOKEN }}
        run: |
          echo "Starting content download..."
          ./scripts/download-content.sh
          echo "Content download completed."

      - name: Debug Git Status
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Git status:"
          git status
          echo "Changed files:"
          git diff --name-status

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "CHANGES_FOUND=true" >> $GITHUB_ENV
            echo "Changes found in the repository"
          else
            echo "CHANGES_FOUND=false" >> $GITHUB_ENV
            echo "No changes found in the repository"
          fi

      - name: Commit changes to main
        if: env.CHANGES_FOUND == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          echo "Adding changes to git..."
          git add .
          
          echo "Committing changes..."
          git commit -m "feat: Update WordPress content from live site"
          
          echo "Pushing to main branch..."
          git push origin main
        
      - name: Create Pull Request to Release
        if: env.CHANGES_FOUND == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release
          branch: main
          title: "Sync WordPress Content from Main to Release"
          body: |
            This PR syncs the latest WordPress content changes from main to release branch.
            
            Changes include:
            - Updated plugins
            - Updated themes
            
            Note: After merging this PR, the activation sync workflow will automatically run.
          delete-branch: true
          labels: |
            automated
            wordpress-sync

      - name: PR Creation Debug
        if: always()
        run: |
          echo "PR Creation Status: ${{ steps.create-pr.outcome }}"
          echo "PR Number: ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.create-pr.outputs.pull-request-url }}" 