name: WordPress Content Sync
# This workflow downloads WordPress content to main branch and creates a PR to release branch
on:
  workflow_dispatch:
    inputs:
      live_site_url:
        description: 'Live Site URL'
        required: true
        default: 'https://wordpress-1000690-5314661.cloudwaysapps.com'
      staging_site_url:
        description: 'Staging Site URL'
        required: true
        default: 'https://techopsautomation.wisdmlabs.net'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create directory structure
        run: |
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes
          
      - name: Make scripts executable
        run: chmod +x scripts/*.sh
        
      - name: Test API Authentication
        run: |
          curl -i -H "Authorization: Basic ${{ secrets.LIVE_SITE_AUTH_TOKEN }}" \
            ${{ github.event.inputs.live_site_url }}/wp-json/techops/v1/plugins/list
          curl -i -H "Authorization: Basic ${{ secrets.STAGING_SITE_AUTH_TOKEN }}" \
            ${{ github.event.inputs.staging_site_url }}/wp-json/techops/v1/plugins/list
            
      - name: Download Content
        env:
          LIVE_SITE_URL: ${{ github.event.inputs.live_site_url }}
          LIVE_SITE_AUTH_TOKEN: ${{ secrets.LIVE_SITE_AUTH_TOKEN }}
          STAGING_SITE_URL: ${{ github.event.inputs.staging_site_url }}
          STAGING_SITE_AUTH_TOKEN: ${{ secrets.STAGING_SITE_AUTH_TOKEN }}
        run: ./scripts/download-content.sh

      - name: Commit changes to main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add wp-content/
          git commit -m "feat: Update WordPress content from live site"
          git push origin main
        
      - name: Create Pull Request to Release
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release
          head: main
          title: 'Sync WordPress Content to Release'
          body: |
            This PR syncs the latest WordPress content changes from main to release branch.
            
            Changes include:
            - Updated plugins
            - Updated themes
            
            Note: After merging this PR, the activation sync workflow will automatically run. 